FortexSrl/FortexSrl/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('administrator123/', admin.site.urls, name="administrador"),
    path('',include('Register.urls')),
    path('',include('Clientes.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('Productos.urls')),
    path('',include('Ordenes.urls')),
    path('',include('Stock.urls')),
]

FortexSrl/Productos/urls.py
from django.urls import path,include
from .views import CreateProductosView,ListProductosView,UpdateProductosView,DeleteProductosView,DetailProductosView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('Productos/create',login_required(CreateProductosView.as_view()),name='createProductos'),
    path('Productos/', login_required(ListProductosView), name='listProductos'),
    path('Productos/update/<int:pk>', login_required(UpdateProductosView.as_view()), name='updateProductos'),
    path('Productos/detail/<int:pk>',login_required(DetailProductosView.as_view()), name='detailProductos'),
    path('Productos/delete/<int:pk>',login_required(DeleteProductosView.as_view()), name='deleteProductos'),
]

FortexSrl/Stock/urls.py
from django.urls import path,include
from .views import ListViewStock,CreateViewStock,CreateView,UpdateStock,ListViewMovimientosStock
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('Stock/',login_required(ListViewStock),name='listStock'),
    path('Stock/update/<int:pk>', login_required(UpdateStock.as_view()), name='updateStock'),
    path('Stock/crear',login_required(CreateViewStock),name='crearStock'),
    path('Stock/crear2/<str:pk>/', login_required(CreateView), name='crearStock2'),
    path('Stock/listMov/', login_required(ListViewMovimientosStock), name='listMov'),

]

FortexSrl/Productos/models.py
from django.db import models
from Clientes.models import Clientes
from simple_history.models import HistoricalRecords
from Register.models import Usuarios
from Stock.models import Stock

# Create your models here.


class Productos(models.Model):

    nombre = models.CharField(blank=False, max_length=50)
    rut = models.ForeignKey(Clientes, on_delete=models.CASCADE)
    material = models.CharField(blank=True, max_length=50)
    plasma = models.CharField(blank=True, max_length=50)
    preTratamiento = models.ManyToManyField(Stock,related_name='+',blank=True)
    fondo = models.ManyToManyField(Stock,related_name="+",blank=True)
    finitura = models.ManyToManyField(Stock,blank=True)
    deposito = models.CharField(blank=True, max_length=150)
    controlCalidad = models.CharField(blank=True, max_length=50)
    embalaje = models.CharField(blank=True, max_length=50)
    consideraciones = models.TextField(blank=True)
    temperatura = models.IntegerField(blank=True,null=True)
    tiempo_horno = models.IntegerField(blank=True,null=True)
    fotos = models.ImageField(blank=True)
    telaio = models.PositiveSmallIntegerField(blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True,blank=True)
    usuarios = models.ForeignKey(Usuarios, verbose_name=("Creado por "), on_delete=models.CASCADE)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.nombre

FortexSrl/Productos/forms.py
from django import forms
from .models import Productos
from Stock.models import Stock

class ProductosForm(forms.ModelForm):
    class Meta:
        model = Productos
        fields = ('nombre','rut','material','preTratamiento','plasma','fondo','deposito','finitura','controlCalidad','embalaje','consideraciones','temperatura','tiempo_horno','fotos','fotos','telaio')

    nombre = forms.CharField()
    rut = forms.SelectMultiple()
    material = forms.CharField()
    preTratamiento = forms.ModelMultipleChoiceField(queryset=Stock.objects.filter(tipo_de_producto='Pre_tratamiento'))
    plasma = forms.CharField()
    fondo = forms.ModelMultipleChoiceField(queryset=Stock.objects.filter(tipo_de_producto="Fondo"))
    deposito = forms.Textarea()
    finitura = forms.ModelMultipleChoiceField(queryset=Stock.objects.filter(tipo_de_producto="Finitura"))
    controlCalidad = forms.Textarea()
    embalaje = forms.CharField()
    consideraciones = forms.Textarea()
    fotos = forms.ImageField(required=False)
    telaio = forms.IntegerField(required=False)

FortexSrl/Productos/views.py
from Register.models import Usuarios
from django.shortcuts import render

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django import forms
from django.views.generic.edit import UpdateView
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import DeleteView
from .forms import ProductosForm
from .models import Productos
from .filters import OrdenesFilter
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


class CreateProductosView(SuccessMessageMixin,CreateView):
    form_class = ProductosForm
    template_name = 'productos/create.html'


    def get_success_url(self):
        return reverse_lazy('listProductos')

    def form_valid(self, form):
        formulario = form.save(commit=False)
        formulario.usuarios = self.request.user

        updated_event = formulario.save()
        messages.success(self.request,'¡¡¡ Producto %s Creado correctamente !!!' %(formulario.nombre))
        return super().form_valid(form)



def ListProductosView(request):
    Model_one = Productos.objects.all()

    myFilter = OrdenesFilter(request.GET, queryset=Model_one)
    paginator = Paginator(myFilter.qs, 10)
    page = request.GET.get('page1')
    try:
        pub = paginator.page(page)
    except PageNotAnInteger:
        pub = paginator.page(1)
    except EmptyPage:
        pub = paginator.page(paginator.num_pages)

    myFilter = OrdenesFilter(request.GET, queryset=Model_one)

    context = {'Model_one': Model_one, 'pub': pub, "myFilter": myFilter}
    return render(request, 'productos/listProductos.html', context)

class UpdateProductosView(SuccessMessageMixin,UpdateView):
    form_class = ProductosForm
    model = Productos
    template_name = 'productos/updateProductos.html'

    def get_success_url(self):
        return reverse_lazy('listProductos')


    def form_valid(self, form):
        formulario = form.save(commit=False)
        messages.success(self.request,'¡¡¡ Producto %s modificado correctamente !!!' %(formulario.nombre))
        return super().form_valid(form)

class DeleteProductosView(DeleteView):
    model = Productos

    def get_success_url(self):

        success_message = '¡¡¡ Producto eliminado correctamente !!!'
        messages.success(self.request,(success_message))
        return reverse_lazy('listProductos')

class DetailProductosView(DetailView):
    form_class = ProductosForm
    model = Productos
    template_name = 'productos/detailProductos.html'

FortexSrl/Productos/templates/productos/create.html
{% extends 'register/index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>


        input[type=number]::-webkit-inner-spin-button {

            -webkit-appearance: none;

            margin: 0;

        }


        .select {
            overflow: hidden;
        }

        input[type=number] {

            -moz-appearance: textfield;

        }

    </style>

{% endblock %}

{% block content %}

    {% if perms.Register.Administrador or perms.Register.Encargado or perms.Register.Secretaria %}

        <div class="container">
            <div class="d-flex justify-content-center">
                <h3>CREARE PRODOTTO</h3>
            </div>
            <hr>
        </div>


        <form method="POST">
            {% csrf_token %}

            <div class="row">

                <div class="col">
                    <div class="container text-center">
                        <label for="nombre" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Nome</strong></h5></label></div>
                    {{ form.nombre|attr:"placeholder:Nome prodotto"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center" }}
                </div>
                <div class="col">
                    <div class="container text-center">
                        <label for="rut" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>P.Iva</strong></h5></label></div>
                    {{ form.rut|attr:"placeholder:P.Iva"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center" }}
                </div>
                <div class="col">
                    <div class="container text-center">
                        <label for="material" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Material</strong></h5></label></div>
                    {{ form.material|attr:"placeholder:Materiale"|add_class:"form-control m-2 font-weight-bold rounded-pill text-center" }}
                </div>

            </div>

            <div class="row">

                <div class="col">
                    <div class="container text-center">
                        <label for="tiempo_horno" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Tempo di Forno</strong></h5></label></div>
                    <div class="input-group m-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text form-control" id="china">M.</span>
                        </div>
                        {{ form.tiempo_horno|attr:"placeholder:Tempo di forno"|add_class:"form-control rounded-pill font-weight-bold font-weight-bold text-center" }}
                    </div>
                </div>

                <div class="col">
                    <div class="container text-center">
                        <label for="temperatura" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Temperatura</strong></h5></label></div>
                    <div class="input-group m-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text form-control" id="china">ºC.</span>
                        </div>
                        {{ form.temperatura|attr:"placeholder:Temperatura"|add_class:"form-control font-weight-bold rounded-pill text-center" }}
                    </div>
                </div>

                <div class="col">
                    <div class="container text-center">
                        <label for="plasma" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Plasma</strong></h5></label></div>
                    {{ form.plasma|attr:"placeholder:Plasma"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center" }}

                </div>

            </div>


            <div class="row">

                <div class="col">
                    <div class="container text-center">
                        <label for="consideraciones" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Considerazioni</strong></h5></label></div>
                    {{ form.consideraciones|attr:"rows:1"|attr:"id:consideraciones"|attr:"placeholder:Considerazioni"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center" }}
                </div>
                <div class="col">
                    <div class="container text-center">
                        <label for="deposito" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Deposito</strong></h5></label></div>
                    {{ form.deposito|attr:"placeholder:Deposito"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center" }}
                </div>
                <div class="col">
                    <div class="container text-center">
                        <label for="embalaje" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Imbalaggio</strong></h5></label></div>
                    {{ form.embalaje|attr:"placeholder:Imbalaggio"|attr:"Imbalaggio"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center" }}
                </div>

            </div>


            <div class="row">
                <div class="col">
                    <div class="container text-center">
                        <label for="controlCalidad" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Controllo di Qualità</strong></h5></label></div>
                    {{ form.controlCalidad|attr:"placeholder:Controllo di qualità"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center" }}
                </div>
                <div class="col">
                    {% if perms.Register.Administrador or perms.Register.Encargado %}
                        <div class="container text-center">
                            <label for="telaio" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Quantità per telaio</strong></h5></label></div>
                        {{ form.telaio|attr:"rows:1"|attr:"id:telaio"|attr:"placeholder:Quantità per telaio"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center" }}
                        </div>
                    {% endif %}
                <div class="col">
                    <div class="custom-file">
                        <div class="container text-center">
                            <label for="fotos" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Imagine</strong></h5></label>
                        </div>
                        {{ form.fotos|attr:"placeholder:File"|add_class:"custom-file-input" }}
                        <label class="custom-file-label mt-5" for="fotos">Scegliere il file</label>
                    </div>
                    <script>$("#id_fotos").on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
                    });
                    </script>
                </div>


            </div>


            <div class="row">
                <div class="col">
                    <div class="container text-center">
                        <label for="preTratamiento" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Pre Tratamiento</strong></h5></label></div>
                    {{ form.preTratamiento|attr:"placeholder:Pre tratamento"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center" }}
                </div>
                <div class="col">
                    <div class="container text-center">
                        <label for="fondo" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Fondo</strong></h5></label></div>
                    {{ form.fondo|attr:"placeholder:Fondo"|attr:"id:fecha_entrega_estimada"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center" }}
                </div>
                <div class="col">
                    <div class="container text-center">
                        <label for="finitura" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Finitura</strong></h5></label></div>
                    {{ form.finitura|attr:"id:finitura"|attr:"placeholder:Finitura"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center" }}
                </div>
            </div>


            <div class="d-flex justify-content-center">

                <a href="javascript:history.back(-1);"
                   class="btn btn-secondary border m-2 rounded-pill" id="jamaica"><strong><i id="japon" class="fas fa-chevron-circle-left"></i> RITORNARE</strong></a>.
                <button type="submit" id="jamaica2" class="btn btn-primary m-2 rounded-pill border"><strong><i id="japon2" class="far fa-paper-plane"></i> INVIARE</strong></button>
            </div>

        </form>


        <script>

            $("#fecha_entrega_estimada").datepicker({
                dateFormat: "dd-mm-yy"
            });
        </script>
        <script>
            document.getElementById("producto").options[0].innerText = "Selezionare un producto...";
            document.getElementById("producto").options[0].disabled = 'true';

            jai = document.getElementById("id_rut").options[0].innerText;
            console.log(jai)

            document.getElementById("id_rut").options[0].innerText = "Selezionare Cliente...";

            document.getElementById("id_rut").options[0].disabled = 'true';

            document.getElementById("asignado").options[0].innerText = "Selezionare chi assegnare...";
            document.getElementById("asignado").options[0].disabled = 'true';

            document.getElementById("estado").options[0].innerText = "Selezionare uno stato...";
            document.getElementById("estado").options[0].disabled = 'true';

            document.getElementById("ubicacion").options[0].innerText = "Selezionare una ubicazione..";
            document.getElementById("ubicacion").options[0].disabled = 'true';


        </script>

    {% else %}
        <div class="justify-content-center">
            <h1 class="text-center">{{ user|upper }} no hai il permesso di accedere a questa pagina</h1>
            <div class="d-flex justify-content-center">
                <a href="javascript:history.back(-1);"
                   class="btn btn-secondary border m-2 rounded-pill text-center"><strong><i class="fas fa-chevron-circle-left"></i> RITORNARE</strong></a>
            </div>
        </div>


    {% endif %}
    <script>
        var hola = document.getElementById("jamaica");
        hola.addEventListener("mouseenter", function (event) {

            var japon = document.getElementById("japon").className = "fas fa-chevron-circle-left fa-spin";

        });
        hola.addEventListener("mouseleave", function (event) {
            var japon = document.getElementById("japon").className = "fas fa-chevron-circle-left";
        });
        var hola2 = document.getElementById("jamaica2");

        hola2.addEventListener("mouseenter", function (event) {

            var japon2 = document.getElementById("japon2").className = "far fa-paper-plane fa-spin";

        });
        hola2.addEventListener("mouseleave", function (event) {
            var japon2 = document.getElementById("japon2").className = "far fa-paper-plane";
        });

        var hola3 = document.getElementById("jamaica3");

        hola3.addEventListener("mouseenter", function (event) {

            var japon3 = document.getElementById("japon3").className = "fas fa-chevron-circle-left fa-spin";

        });
        hola3.addEventListener("mouseleave", function (event) {
            var japon3 = document.getElementById("japon3").className = "fas fa-chevron-circle-left";
        });
    </script>
{% endblock %}

FortexSrl/Productos/templates/productos/updateProductos.html
{%extends 'register/index.html'%}
{%load static%}
{% load widget_tweaks %}
{%block head%}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<style>


    input[type=number]::-webkit-inner-spin-button {

        -webkit-appearance: none;

        margin: 0;

    }


    .select {
        overflow: hidden;
    }

    input[type=number] {

        -moz-appearance: textfield;

    }

</style>

{%endblock%}

{%block content%}

{%if perms.Register.Administrador or perms.Register.Encargado or perms.Register.Secretaria%}

<div class="container">
    <div class="d-flex justify-content-center">
        <h3>CREARE PRODOTTO</h3>
    </div>
    <hr>
</div>


<form method="POST">
    {%csrf_token%}

    <div class="row">

        <div class="col">
            <div class="container text-center">
                <label for="nombre" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Nome</strong></h5></label></div>
            {{form.nombre|attr:"placeholder:Nome prodotto"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center"}}
        </div>
        <div class="col">
            <div class="container text-center">
                <label for="rut" style="margin-bottom:-5rem;margin-top:1rem" id="id_rut"><h5><strong>P.Iva</strong></h5></label></div>
            {{form.rut|attr:"placeholder:P.Iva"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center"}}
        </div>
        <div class="col">
            <div class="container text-center">
                <label for="material" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Material</strong></h5></label></div>
            {{form.material|attr:"placeholder:Materiale"|add_class:"form-control m-2 font-weight-bold rounded-pill text-center"}}
        </div>

    </div>

    <div class="row">

        <div class="col">
            <div class="container text-center">
                <label for="tiempo_horno" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Tempo di Forno</strong></h5></label></div>
            <div class="input-group m-2">
                <div class="input-group-prepend">
                    <span class="input-group-text form-control" id="china">M.</span>
                </div>
                {{form.tiempo_horno|attr:"placeholder:Tempo di forno"|add_class:"form-control rounded-pill font-weight-bold font-weight-bold text-center"}}
            </div>
        </div>

        <div class="col">
            <div class="container text-center">
                <label for="temperatura" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Temperatura</strong></h5></label></div>
            <div class="input-group m-2">
                <div class="input-group-prepend">
                    <span class="input-group-text form-control" id="china">ºC.</span>
                </div>
                {{form.temperatura|attr:"placeholder:Temperatura"|add_class:"form-control font-weight-bold rounded-pill text-center"}}
            </div>
        </div>

        <div class="col">
            <div class="container text-center">
                <label for="plasma" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Plasma</strong></h5></label></div>
            {{form.plasma|attr:"placeholder:Plasma"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center"}}

        </div>

    </div>



    <div class="row">

        <div class="col">
                        <div class="container text-center">
                            <label for="consideraciones" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Consideraciones</strong></h5></label></div>
            {{form.consideraciones|attr:"rows:1"|attr:"id:consideraciones"|attr:"placeholder:Finitura"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center"}}
        </div>
                <div class="col">
            <div class="container text-center">
                <label for="deposito" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Deposito</strong></h5></label></div>
            {{form.deposito|attr:"placeholder:Deposito"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center"}}
        </div>
        <div class="col">
            <div class="container text-center">
                <label for="embalaje" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Imbalaggio</strong></h5></label></div>
            {{form.embalaje|attr:"placeholder:Imbalaggio"|attr:"Imbalaggio"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center"}}
        </div>

    </div>


    <div class="row">
        <div class="col">
                        <div class="container text-center">
                            <label for="controlCalidad" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Controllo di Qualità</strong></h5></label></div>
            {{form.controlCalidad|attr:"placeholder:Controllo di qualità"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center"}}
        </div>
        <div class="col">
            <div class="container text-center">
                <label for="telaio" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Quantità per telaio</strong></h5></label></div>
            {{form.telaio|attr:"rows:1"|attr:"id:telaio"|attr:"placeholder:Quantità per telaio"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center"}}
        </div>
        <div class="col">
            <div class="custom-file">
            <div class="container text-center">
                    <label for="fotos" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Imagine</strong></h5></label>
                </div>
                {{form.fotos|attr:"placeholder:File"|add_class:"custom-file-input"}}
                <label class="custom-file-label mt-5" for="fotos">Scegliere il file</label>
            </div>
            <script>$("#id_fotos").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
            </script>
        </div>


    </div>


    <div class="row">
        <div class="col">
                        <div class="container text-center">
                            <label for="preTratamiento" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong>Pre Tratamiento</strong></h5></label></div>
            {{form.preTratamiento|attr:"placeholder:Pre tratamento"|add_class:"form-control font-weight-bold rounded-pill m-2 text-center"}}
        </div>
        <div class="col">
                        <div class="container text-center">
                            <label for="fondo" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Fondo</strong></h5></label></div>
            {{form.fondo|attr:"placeholder:Fondo"|attr:"id:fecha_entrega_estimada"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center"}}
        </div>
        <div class="col">
                        <div class="container text-center">
                            <label for="finitura" style="margin-bottom:-5rem;margin-top:1rem"><h5><strong> Finitura</strong></h5></label></div>
            {{form.finitura|attr:"id:finitura"|attr:"placeholder:Finitura"|add_class:"form-control rounded-pill m-2 font-weight-bold font-weight-bold text-center"}}
        </div>
    </div>


    <div class="d-flex justify-content-center">

        <a href="javascript:history.back(-1);"
           class="btn btn-secondary border m-2 rounded-pill" id="jamaica"><strong><i id="japon" class="fas fa-chevron-circle-left"></i> RITORNARE</strong></a>.
        <button type="submit" id="jamaica2" class="btn btn-primary m-2 rounded-pill border"><strong><i id="japon2" class="far fa-paper-plane"></i> INVIARE</strong></button>
    </div>

</form>


<script>

    $("#fecha_entrega_estimada").datepicker({
        dateFormat: "dd-mm-yy"
    });
</script>
<script>
    document.getElementById("producto").options[0].innerText = "Selezionare un producto...";
    document.getElementById("producto").options[0].disabled = 'true';

    document.getElementById("id_rut").options[0].innerText = "Selezionare Cliente...";
    document.getElementById("id_rut").options[0].disabled = 'true';

    document.getElementById("asignado").options[0].innerText = "Selezionare chi assegnare...";
    document.getElementById("asignado").options[0].disabled = 'true';

    document.getElementById("estado").options[0].innerText = "Selezionare uno stato...";
    document.getElementById("estado").options[0].disabled = 'true';

    document.getElementById("ubicacion").options[0].innerText = "Selezionare una ubicazione..";
    document.getElementById("ubicacion").options[0].disabled = 'true';


</script>

{%else%}
<div class="justify-content-center">
    <h1 class="text-center">{{user|upper}} no hai il permesso di accedere a questa pagina</h1>
    <div class="d-flex justify-content-center">
        <a href="javascript:history.back(-1);"
           class="btn btn-secondary border m-2 rounded-pill text-center"><strong><i class="fas fa-chevron-circle-left"></i> RITORNARE</strong></a>
    </div>
</div>


{%endif%}
<script>
    var hola = document.getElementById("jamaica");
    hola.addEventListener("mouseenter", function (event) {

        var japon = document.getElementById("japon").className = "fas fa-chevron-circle-left fa-spin";

    });
    hola.addEventListener("mouseleave", function (event) {
        var japon = document.getElementById("japon").className = "fas fa-chevron-circle-left";
    });
    var hola2 = document.getElementById("jamaica2");

    hola2.addEventListener("mouseenter", function (event) {

        var japon2 = document.getElementById("japon2").className = "far fa-paper-plane fa-spin";

    });
    hola2.addEventListener("mouseleave", function (event) {
        var japon2 = document.getElementById("japon2").className = "far fa-paper-plane";
    });

    var hola3 = document.getElementById("jamaica3");

    hola3.addEventListener("mouseenter", function (event) {

        var japon3 = document.getElementById("japon3").className = "fas fa-chevron-circle-left fa-spin";

    });
    hola3.addEventListener("mouseleave", function (event) {
        var japon3 = document.getElementById("japon3").className = "fas fa-chevron-circle-left";
    });
</script>
{%endblock%}